# Machine Learning Lab Tutorial 1

## Setting up the Environment

1. Open a terminal/command prompt on your machine.
2. Go to the folder where you wish to save your tutorials using the command: cd path/to/your/folder 
3. Create a New Conda Environment with NumPy Installed using: conda create -n MLLab numpy 
4. Activate the Newly Created Conda Environment using conda activate MLLab 
5. Install Jupyter Notebook in the Environment using: conda install notebook 
6. Launch Jupyter Notebook using: jupyter-notebook
7. This will start the Jupyter Notebook server and should automatically open a new tab or window in the default web browser showing the Jupyter Notebook interface.

## Import the Libraries




In [15]:
import numpy as np

#### If this command runs without any errors, it means your library has been successfully imported.

## Matrix Operations using Numpy

### 1. Define matrices

#### Let's define a 2x2 matrix A:


In [16]:
A=np.array([[1,2],[3,4]])

#### Let's see the value of A:

##### Way 1

In [17]:
A

array([[1, 2],
       [3, 4]])

##### Way 2

In [18]:
print(A)

[[1 2]
 [3 4]]


#### Let's define a 2x2 matrix B:

In [19]:
B=np.array([[5,6],[7,8]])

In [20]:
B

array([[5, 6],
       [7, 8]])

#### We want to see what happens when we try to see values of 2 variables in one cell without print statement

In [21]:
A
B

array([[5, 6],
       [7, 8]])

#### We see that only matrix B gets shown on the screen.

In [22]:
#### We want to see what happens when we try to see values of 2 variables in one cell With print statement.

In [23]:
print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]


#### We see that both the matrices get printed with the print statement.

#### Now let's define a 3x3 matrix C:

In [24]:

C=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [25]:
C

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 2. To see variables defined in scope:

In [27]:
whos


Variable   Type       Data/Info
-------------------------------
A          ndarray    2x2: 4 elems, type `int64`, 32 bytes
B          ndarray    2x2: 4 elems, type `int64`, 32 bytes
C          ndarray    3x3: 9 elems, type `int64`, 72 bytes
np         module     <module 'numpy' from '/op<...>kages/numpy/__init__.py'>


### 3. Check datatype of matrices:

In [28]:
A.dtype

dtype('int64')

In [29]:
print("Data type Matrix A:")
print(A.dtype)

print("\nData type Matrix B:")
print(B.dtype)

print("\nData type Matrix C:")
print(C.dtype)

Data type Matrix A:
int64

Data type Matrix B:
int64

Data type Matrix C:
int64


#### Define matrix G of type doubles and size 2x3:

In [30]:
G=np.array([[1,2,3],[4,5,6]],np.double)
G

array([[1., 2., 3.],
       [4., 5., 6.]])

In [31]:
print(G.dtype)

float64


In [32]:
whos

Variable   Type       Data/Info
-------------------------------
A          ndarray    2x2: 4 elems, type `int64`, 32 bytes
B          ndarray    2x2: 4 elems, type `int64`, 32 bytes
C          ndarray    3x3: 9 elems, type `int64`, 72 bytes
G          ndarray    2x3: 6 elems, type `float64`, 48 bytes
np         module     <module 'numpy' from '/op<...>kages/numpy/__init__.py'>


### 4. Define Zero and Identity Matrix:

#### To define zero matrix of size 4x4:

In [34]:
Z_4=np.zeros(shape=(4,4)) ## In NumPy, the default data type for numbers in an array created by np.zeros is float64.
Z_4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### If you want Zero matrix, that has integer values:

In [36]:
Z4=np.zeros(shape=(4,4),dtype=int)
Z4

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

#### To define Identity matrix of size 4x4:

In [37]:
I_4=np.identity(4)
I_4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### To define Identity Matrix of type int:

In [40]:
I4=np.identity(4,dtype=int)
I4

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

#### Another approach to define identity:

In [41]:
I_3=np.eye(3,3)
I_3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 5. Access rows and columns of a matrix:

#### In Python, indices start from [0,0]

#### If we want to access the first element of a matrix, we will use indices [0,0]

In [43]:
print("Matrix C:")
print(C)

print("\nFirst element of Matrix C:")
print(C[0,0])

Matrix C:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

First element of Matrix C:
1


#### Let's modify this element:

In [44]:

C[0,0]=7

print("First element of Matrix C:")
print(C[0,0])

print("\nMatrix C:")
print(C)

First element of Matrix C:
7

Matrix C:
[[7 2 3]
 [4 5 6]
 [7 8 9]]


#### Let's change it back to its original value:

In [46]:
C[0,0]=1
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Let's access first row of a matrix:

#### first index denotes row: Matrix[row,column]

In [49]:
C[0,:]


array([1, 2, 3])

In [50]:
print("First row of Matrix C:")
print(C[0,:])


First row of Matrix C:
[1 2 3]


#### Let's access entries on the third row of matrix C:

In [52]:
print("Third row of Matrix C:")
print(C[2,:])

Third row of Matrix C:
[7 8 9]


#### Let's retrieve 2nd column of matrix C:

In [53]:
print("Second column of Matrix C:")
print(C[:,1])

Second column of Matrix C:
[2 5 8]


#### Retrieve Matrix Blocks:

In [54]:
#### Let's retrieve elements with values 1,2,4,5 from C:

In [47]:
print(C[0:2,0:2])



[[1 2]
 [4 5]]


##### Note: 0:2 doesn't include 2 (only 0 and 1)

#### Now Let's retrieve elements with values 5,6,8,9 from C:

##### rows requires= 1 and 2, Columns= 1 and 2. We Can't define end easily. Hence, leave it blank.

In [55]:
print(C[1:,1:])


[[5 6]
 [8 9]]


In [56]:
print (C[1:2,1:2])


[[5]]


##### [1:2,1:2] only gives us the center most element in the matrix

#### Another approach to get elements with values 5,6,8,9:

In [52]:
print(C[-2:,-2:])

[[5 6]
 [8 9]]


##### What we did above is called slicing.

In [57]:
whos

Variable   Type       Data/Info
-------------------------------
A          ndarray    2x2: 4 elems, type `int64`, 32 bytes
B          ndarray    2x2: 4 elems, type `int64`, 32 bytes
C          ndarray    3x3: 9 elems, type `int64`, 72 bytes
G          ndarray    2x3: 6 elems, type `float64`, 48 bytes
I4         ndarray    4x4: 16 elems, type `int64`, 128 bytes
I_3        ndarray    3x3: 9 elems, type `float64`, 72 bytes
I_4        ndarray    4x4: 16 elems, type `float64`, 128 bytes
Z4         ndarray    4x4: 16 elems, type `int64`, 128 bytes
Z_4        ndarray    4x4: 16 elems, type `float64`, 128 bytes
np         module     <module 'numpy' from '/op<...>kages/numpy/__init__.py'>


#### Find the no. of rows and columns of a matrix:

#### Lets find for matrix G:

In [54]:
print(G)
print(G.shape)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)


#### Let's find no. of rows in G:

In [58]:
print("No. of rows in G:")
print(G.shape[0])

No. of rows in G:
2


#### Let's find no. of columns in G:

In [60]:
print("No. of columns in G:")
print(G.shape[1])

No. of columns in G:
3


### 6. Matrix Transpose:

In [59]:
print("Matrix G is:")
print(G)

print("\ntranspose of matrix G is:")
print(G.T)

Matrix G is:
[[1. 2. 3.]
 [4. 5. 6.]]

transpose of matrix G is:
[[1. 4.]
 [2. 5.]
 [3. 6.]]


### 7. Adding two matrices

#### Let's add A and B:

In [62]:
S=A+B
print("A is:\n", A)
print("B is:\n", B)
print("Sum of A and B is:\n", S)

A is:
 [[1 2]
 [3 4]]
B is:
 [[5 6]
 [7 8]]
Sum of A and B is:
 [[ 6  8]
 [10 12]]


### 8. Let's multiply matrix by a scalar:

In [63]:
MM=2*A
print("A is:\n",A)

print("All elements of A multiplied by 2 is\n", MM)

A is:
 [[1 2]
 [3 4]]
All elements of A multiplied by 2 is
 [[2 4]
 [6 8]]


### 9. Let's learn how to multiply two matrices:

In [74]:
M=A*B
print ("M is\n",M)
print("\nA is\n", A)
print("\nB is \n", B)

print("\nM seems to be the element wise multiplcation of A and B, but not matrix multiplication :(\n",M)


M is
 [[ 5 12]
 [21 32]]

A is
 [[1 2]
 [3 4]]

B is 
 [[5 6]
 [7 8]]

M seems to be the element wise multiplcation of A and B, but not matrix multiplication :(
 [[ 5 12]
 [21 32]]


##### Star operator multiplies two matrices elementwise, and we don't want this.

#### Correct way to multiply two matrices:

In [65]:
M1=A.dot(B)
print("A is\n", A)
print("\nB is\n", B)
print("\nMatrix multiplication of A and B is\n", M1)

A is
 [[1 2]
 [3 4]]

B is
 [[5 6]
 [7 8]]

Matrix multiplication of A and B is
 [[19 22]
 [43 50]]


#### 2nd way to multiply two matrices:

In [66]:
M2=np.matmul(A,B)
print("\nSecond way of Matrix multiplication of A and B is\n", M2)


Second way of Matrix multiplication of A and B is
 [[19 22]
 [43 50]]


#### 3rd way:

In [68]:
M3=A@B
print("\nThird way of Matrix multiplication of A and B is\n", M3)



Third way of Matrix multiplication of A and B is
 [[19 22]
 [43 50]]


### 10. Matrix Inverse:

In [70]:
whos

Variable   Type       Data/Info
-------------------------------
A          ndarray    2x2: 4 elems, type `int64`, 32 bytes
B          ndarray    2x2: 4 elems, type `int64`, 32 bytes
C          ndarray    3x3: 9 elems, type `int64`, 72 bytes
G          ndarray    2x3: 6 elems, type `float64`, 48 bytes
I4         ndarray    4x4: 16 elems, type `int64`, 128 bytes
I_3        ndarray    3x3: 9 elems, type `float64`, 72 bytes
I_4        ndarray    4x4: 16 elems, type `float64`, 128 bytes
M1         ndarray    2x2: 4 elems, type `int64`, 32 bytes
M2         ndarray    2x2: 4 elems, type `int64`, 32 bytes
M3         ndarray    2x2: 4 elems, type `int64`, 32 bytes
MM         ndarray    2x2: 4 elems, type `int64`, 32 bytes
S          ndarray    2x2: 4 elems, type `int64`, 32 bytes
X          ndarray    2x4: 8 elems, type `int64`, 64 bytes
Z4         ndarray    4x4: 16 elems, type `int64`, 128 bytes
Z_4        ndarray    4x4: 16 elems, type `float64`, 128 bytes
np         module     <module 'nump

#### Let's calculate inverse of matrix A:

In [71]:
A1=np.linalg.inv(A)

#### Check if A1 is the inverse of A:

##### If A1 is the inverse of A: A1@A=A@A1=Identity matrix

In [73]:
print(A@A1)

[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


##### Don't be confused by e^-16, it is effectively zero

### 11. Save matrix to a file:

#### first argument in the function save is the name of the file and second argument is the variable name.

In [75]:
np.save('matrix_file.npy',G)

#### Let's load the saved file:

In [76]:
G4=np.load('matrix_file.npy')

#### Let's compare both matrices using the boolean operator ==

In [86]:
print(G4==G)

[[ True  True  True]
 [ True  True  True]]


##### All elements of G4 are equal to G.